"use client";
import "src/styles/globals.css";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import serviceApolloClient from "@/services/apolloClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider client={serviceApolloClient}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
